import type { GameRoster } from "@/types/roster";
import rosters from "@/data/generated/players.json";

// Generated by scripts/sync-airtable.ts — keyed by title slug.
const ROSTERS = rosters as unknown as Record<string, GameRoster>;

export function rosterFor(slug: string): GameRoster {
  return ROSTERS[slug] ?? [];
}
